services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /var/www/serverstuck/serverstuck-template:/app
    env_file:
      - .env.local
