services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.local
  #   networks:
  #     - backend
  # networks:
  #   backend:
  #     driver: bridge
